language: java

addons:
  sonarcloud:
    organization: "sergiopsinformatico-github"
    token:
      secure: "s40fdf35a68ff4d3178bad0830c5f4ad549c42b3f"
      
script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=sergiopsinformatico_Aplicacion-Flashcards

jdk:
  - oraclejdk8

dist: trusty

deploy:
  provider: heroku
  api_key:
    secure: f981ae17-fd60-4d23-845b-0b3e99f2ec1e
  app: aplicacion-flashcards
  on:
    repo: sergiopsinformatico/Aplicacion-Flashcards
    branch: ramaSprint2