language: java

addons:
  sonarcloud:
    organization: "sergiopsinformatico-github"
    token:
      secure: "3a40f7ce79b62c41505d6d661028d0949358ea1c"

script:
  - mvn clean verify -P sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=sergiopsinformatico-github -Dsonar.login=3a40f7ce79b62c41505d6d661028d0949358ea1c -Dsonar.branch.name=master -Dsonar.sources=pom.xml,src/main/java/aplicacionflashcards/auxiliares,src/main/java/aplicacionflashcards/broker,src/main/java/aplicacionflashcards/controladores,src/main/java/aplicacionflashcards/db/dao,src/main/java/aplicacionflashcards/db/mongodb,src/main/java/aplicacionflashcards/dto,src/main/resources,src/test/java/aplicacionflashcards/runner,src/test/java/aplicacionflashcards/features,src/test/java/aplicacionflashcards/stepDefinitions

jdk:
  - oraclejdk8

dist: trusty

deploy:
  provider: heroku
  api_key:
    secure: f981ae17-fd60-4d23-845b-0b3e99f2ec1e
  app: aplicacion-flashcards
  on:
    repo: sergiopsinformatico/Aplicacion-Flashcards
    branch: master