language: java

jdk:
  - oraclejdk8

dist: trusty

deploy:
  provider: heroku
  api_key:
    secure: f981ae17-fd60-4d23-845b-0b3e99f2ec1e
  app: aplicacion-flashcards
  on:
    repo: sergiopsinformatico/Aplicacion-Flashcards
    branch: ramaSprint2